### ISSUE TITLE
Do you have the code of the original UNet given by ZTE?

### ISSUE THREAD

**Issue by Ssakura-go** [xiaowukongkong/zxpy#1]

**Comment by xiaowukongkong** [comment]
中兴给的代码我删掉了，抱歉



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 10, 2022 17:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [xiaowukongkong/zxpy] Do you have the code of the original UNet givenby ZTE? (Issue #1)




 
Dear friend,
 Hello,
 
I'm glad to find out that you were one of the participator in the competition organized by ZTE. I need to compare my network with the code of the original UNet. However, I couldn't find out the code on my PC.
 
If you have the code, could you please share it with me?
 Thank you for listening!
